In [2]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame

In [3]:
arr1 = np.arange(9).reshape(3,3)
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [4]:
np.concatenate([arr1,arr1], axis=1)

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [6, 7, 8, 6, 7, 8]])

In [5]:
np.concatenate([arr1,arr1], axis=0)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [7]:
ser1 = Series([0,1,2], index=['T','U','V'])
ser2 = Series([3,4], index=['X','Y'])
ser1

T    0
U    1
V    2
dtype: int64

In [8]:
ser2

X    3
Y    4
dtype: int64

In [10]:
pd.concat([ser1,ser2])

T    0
U    1
V    2
X    3
Y    4
dtype: int64

In [12]:
pd.concat([ser1,ser2], axis=1, sort=True)

0    1
T  0.0  NaN
U  1.0  NaN
V  2.0  NaN
X  NaN  3.0
Y  NaN  4.0

In [13]:
#to add markers or keys to concat results
pd.concat([ser1, ser2], keys=['cat1', 'cat2'])

cat1  T    0
      U    1
      V    2
cat2  X    3
      Y    4
dtype: int64

In [14]:
df1 = DataFrame(np.random.randn(4,3), columns=['X','Y','Z'])
df1

X         Y         Z
0 -0.121908  0.481987 -0.457279
1  0.490836  0.455065  0.362136
2 -0.055716 -1.257831  0.447466
3  0.945615  1.079011  0.815866

In [15]:
df2 = DataFrame(np.random.randn(3,3), columns=['Y','Q','X'])
df2

Y         Q         X
0  0.232865 -0.202851 -1.185347
1  0.274414 -1.881726  1.111745
2  0.094087  0.168630  1.318495

In [17]:
pd.concat([df1, df2], sort=True)

Q         X         Y         Z
0       NaN -0.121908  0.481987 -0.457279
1       NaN  0.490836  0.455065  0.362136
2       NaN -0.055716 -1.257831  0.447466
3       NaN  0.945615  1.079011  0.815866
0 -0.202851 -1.185347  0.232865       NaN
1 -1.881726  1.111745  0.274414       NaN
2  0.168630  1.318495  0.094087       NaN

In [18]:
# To keep the index going
pd.concat([df1, df2], ignore_index=True, sort=True)

Q         X         Y         Z
0       NaN -0.121908  0.481987 -0.457279
1       NaN  0.490836  0.455065  0.362136
2       NaN -0.055716 -1.257831  0.447466
3       NaN  0.945615  1.079011  0.815866
4 -0.202851 -1.185347  0.232865       NaN
5 -1.881726  1.111745  0.274414       NaN
6  0.168630  1.318495  0.094087       NaN

# Combining DataFrames

In [19]:
ser1 = Series([2,np.nan,4,np.nan,6,np.nan],
              index=['Q','R','S','T','U','V'])
ser1

Q    2.0
R    NaN
S    4.0
T    NaN
U    6.0
V    NaN
dtype: float64

In [20]:
ser2 = Series(np.arange(len(ser1)), dtype=np.float64,
              index=['Q','R','S','T','U','V'])
ser2

Q    0.0
R    1.0
S    2.0
T    3.0
U    4.0
V    5.0
dtype: float64

In [21]:
Series(np.where(pd.isnull(ser1), ser2, ser1), index=ser1.index)

Q    2.0
R    1.0
S    4.0
T    3.0
U    6.0
V    5.0
dtype: float64

In [22]:
ser1.combine_first(ser2)

Q    2.0
R    1.0
S    4.0
T    3.0
U    6.0
V    5.0
dtype: float64

In [23]:
nan=np.nan
df_odds = DataFrame({'X':[1.,nan,3.,nan],
                     'Y':[nan,5.,nan,7.],
                     'Z':[nan,9,nan,11]})
df_odds

X    Y     Z
0  1.0  NaN   NaN
1  NaN  5.0   9.0
2  3.0  NaN   NaN
3  NaN  7.0  11.0

In [24]:
df_evens = DataFrame({'X':[2.,4.,nan,6.,8.],
                      'Y':[nan,10.,12.,14.,16.]})
df_evens

X     Y
0  2.0   NaN
1  4.0  10.0
2  NaN  12.0
3  6.0  14.0
4  8.0  16.0

In [25]:
df_odds.combine_first(df_evens)

X     Y     Z
0  1.0   NaN   NaN
1  4.0   5.0   9.0
2  3.0  12.0   NaN
3  6.0   7.0  11.0
4  8.0  16.0   NaN